---

name: Lint
on:
  push

jobs:
  pylint-check:
    runs-on: ubuntu-latest
    steps:
      # Get system info
      - run: ifconfig
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: echo "GitHub branch is ${{ github.ref }}"

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      -  run: pip install autopep8 yamllint pylint
      # install linting
      # - run: pip install autopep8 yamllint pylint

      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@v3

      
      # run lint.sh
      - run: ./lint.sh