---

name: Check linting and tests
on:
  push

jobs:
  pylint-pytest:
    runs-on: ubuntu-latest
    steps:
      # Get system info
      - run: ifconfig
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: echo "GitHub branch is ${{ github.ref }}"

      # - name: Setup Python
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: '3.10'
      # - run: pip install autopep8 yamllint pylint pytest

      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it
      - name: Setup Python dependencies
        uses: actions/checkout@v3
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt

      # Run autopep8 and pylint
      - run: ./lint.sh

      # Run test on fresh genesis
      - run: python -m pytest -v -s

