---

name: Check linting and tests
on:
  push

jobs:
  pylint-pytest:
    runs-on: ubuntu-latest
    steps:
      # Get system info
      - run: ifconfig
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: echo "GitHub branch is ${{ github.ref }}"

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      # Setup Python dependencies
      - run: python -m pip install -r requirements.txt

      # Run autopep8 and pylint
      - run: ./lint.sh

      # Run test on fresh genesis
      - run: python -m pytest -v -s

